apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: megamon-system
data:
  config.json: |
    {
      "MetricsPrefix": "megamon.slicedev",
      "AggregationIntervalSeconds": 5,
      "EventsBucketName": "myproj-megamon-events",
      "DisableNodePoolJobLabelling": true,
      "SliceEnabled": true,
      "UnknownCountThreshold": 0.0,
      "GKE": {
        "ProjectId": "myproj",
        "ClusterName": "gke-cluster",
        "ClusterLocation": "us-central1"
      }
    }
