apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: megamon@cool-machine-learning.iam.gserviceaccount.com
  name: megamon-controller-manager
  namespace: megamon-system